---
- hosts: web23 # server web23 provision
  become: true
  tasks:
  - name: web23:set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow
  - name: web23:nginx
    dnf:
      name: nginx
      state: latest
  - name: web23:nginx start
    systemd:
      name: nginx
      state: started
  - name: web23:firewalld http,https
    firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - http
      - https
      
- hosts: log23  # server log23  provision
  become: true
  tasks:
  - name: log23:firewalld syslog
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - 514/udp
      - 514/tcp

