---
- hosts: web23 # server web23 provision
  become: true
  tasks:
  - name: web23:set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow
  - name: web23:nginx,audispd-plugins
    dnf:
      name:
        - nginx
        - audispd-plugins
      state: latest
  - name: web23:nginx start
    systemd:
      name: nginx
      state: started
  - name: web23:firewalld http,https
    firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - http
      - https
  - name: nginx conf file and  restart
    template:
      src: up/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'
    notify:
      - restart nginx      
  - name: audit.rules conf file and  restart
    template:
      src: up/audit.rules
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: '0644'
    notify:
      - restart auditd
      
  handlers: 
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes 
    - name: restart auditd
      command: service auditd restart
      
- hosts: log23  # server log23  provision
  become: true
  tasks:
  - name: log23:firewalld syslog,auditd
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - 514/udp
      - 514/tcp
      - 60/tcp
  - name: rsyslog conf file and  restart
    template:
      src: up/rsyslog.conf
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: '0644'
    notify:
      - restart rsyslog
  handlers:
    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted
        enabled: yes 
