---
- hosts: web23 # server ns01 provision
  become: true
  tasks:
  - name: web23:set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow
  - name: web23:nginx
    dnf:
      name: nginx
      state: latest
  - name: web23:nginx start
    systemd:
      name: nginx
      state: started
  - name: web23:firewalld http 
    firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
  - name: web23:firewalld https 
    firewalld:
      service: https
      permanent: true
      immediate: true
      state: enabled
 
