---
- hosts: web23 # server ns01 provision
  become: true
  tasks:
  - name: web23:set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow
  - name: web23:nginx
    dnf:
      name: nginx
      state: latest
  - name: web23:nginx start
    systemd:
      name: nginx
      state: started
  - name: web23:firewalld http,https 
    firewalld:
      service: http,https
      permanent: true
      immediate: true
      state: enabled
 
